import { Inter } from "@next/font/google";
import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utilities/requests";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ movies }) {
  console.log(movies);
  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results movies={movies} />
    </>
  );
}

// /movie/top_rated?api_key=${api_key}&language=en-US

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  try {
    const response = await fetch(
      `https://api.themoviedb.org/3${
        requests[genre]?.url || requests.fetchTrending.url
      }
    `
    );
    const data = await response.json();

    return {
      props: {
        movies: data.results,
      },
    };
  } catch (error) {
    console.log(error.message);
  }
}
